[package]
name = "rust-microservice"
version = "0.1.0"
authors = ["Paul Hale <paul@domainscanners.com>"]
edition = "2018"

[dependencies]
hyper = "0.12.27"
futures = "0.1.26"
slab = "0.4.2"
regex = "1.1.6"
lazy_static = "1.3.0"
